#ifndef __AIMEI_DATA_LOG_2_DB_DEF_H__
#define __AIMEI_DATA_LOG_2_DB_DEF_H__
enum KSHOW_MONEY_OPER_TYPE { 
	MONEY_QUERY = 0,
	MONEY_PRE_SUB,
	MONEY_BE_USED,
	MONEY_WRITE_OFF,
	MONEY_PAY_MOBILE
};

enum AIMEI_PRODUCT_TYPE {
	AIMEI_PRODUCT_TYPE_MINIK = 0,
	AIMEI_PRODUCT_TYPE_KSHOW
};

enum AIMEI_TERMINAL_TYPE {
	AIMEI_TERMINAL_TYPE_MACHINE = 0,
	AIMEI_TERMINAL_TYPE_MOB
};

enum AIMEI_USER_ACTION_TYPE {
	AIMEI_USER_ACTION_TYPE_PLAY = 0,
	AIMEI_USER_ACTION_TYPE_LOGIN,
	AIMEI_USER_ACTION_TYPE_LOGOUT,
	AIMEI_USER_ACTION_TYPE_CONSUME,
	AIMEI_USER_ACTION_TYPE_CLICK,
	AIMEI_USER_ACTION_TYPE_PREVIEW
};

enum KSHOW_MONEY_ID_TYPE {
	MONEY_ID_CASH = 0,
	MONEY_ID_K_GOLD_COIN,
	MONEY_ID_K_SILVER_COIN,
	MONEY_ID_K_MUSIC_JIFEN,
	MONEY_ID_WEIXIN_PAY,
	MONEY_ID_ALI_PAY,
	MONEY_ID_FREE_TICKET
};

#endif
